webform_securepay.settings:
  type: config_object
  label: 'SecurePay settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    merchant_code:
      type: string
      label: 'Merchant Code'
    environment:
      type: string
      label: 'Environment'
    currency:
      type: string
      label: 'Default Currency'
    dcc_enabled:
      type: boolean
      label: 'Enable Dynamic Currency Conversion'
    three_ds_enabled:
      type: boolean
      label: 'Enable 3D Secure 2'